### ISSUE TITLE
gocertifi is detected as "Do What The F*ck You Want To Public License"

### ISSUE THREAD

**Issue by nicolas-grekas** [certifi/gocertifi#13]
While the repo is MPL2
https://github.com/certifi/gocertifi

**Comment by mattrobenolt** [comment]
Detected by what?

**Comment by mattrobenolt** [comment]
Closing this since the LICENSE is very clearly MPL2 and GitHub even detects it as so. But I am also not a laywer, so if something else is up, lemme know.
