### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by mattrobenolt** [certifi/gocertifi#25]
@Lukasa I'm not sure who all has permission, but I don't. So mind doing this or handing over the keys so I can? :sunglasses: 

Thanks!

I think we definitely want to go this route: https://github.com/github/renaming#renaming-existing-branches so it doesn't break existing users that depended on `master`,

**Comment by Lukasa** [comment]
You should have the branch-fu now.

**Comment by mattrobenolt** [comment]
Done, thanks! <3
