### ISSUE TITLE
Go Daddy Certificate Not Recognized

### ISSUE THREAD

**Issue by sundarv85** [certifi/gocertifi#30]
Hi there,

I'm trying to download 

https://app.cypresstruck.com/appResources.js

and I'm passing gocertifi in transport layer. I get the error 

`x509: certificate signed by unknown authority`

but, this works from Chrome Browser - saying it is from Go Daddy signed. What am I missing here?

**Comment by sundarv85** [comment]
![image](https://user-images.githubusercontent.com/11090193/141862048-f3208add-a940-4ad1-9a90-fb7dd1f90abd.png)

**Comment by dolmen** [comment]
Which version of `gocertifi` do you use? `grep gocertifi go.mod` in your project.

**Comment by dolmen** [comment]
Note that the certificate on the screenshot was marked expiring on Nov 24th.

The certificate that I see today is marked as valid from Sun, 05 Dec 2021 14:25:44 UTC to Mon, 29 Aug 2022 18:12:24 UTC.

So I can safely assume that there was a certificate problem on that server.

@sundarv85 Could you confirm this is fixed now?

**Comment by sundarv85** [comment]
Yes, this is now fixed. Thank you.
